# -*- coding: utf-8 -*-
"""Tugas_Jobsheet10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ukw-XItKxB_fsDQ9dlhSxsFTRm0h8ECB
"""

import pandas as pd
raw_file = 'svm_mushrooms.csv'
raw_data = pd.read_csv(raw_file)
raw_data.head()
# kita encode raw data supaya berubah menjadi angka semua
encoded_data = pd.get_dummies(raw_data)
# kita lihat isi data kita yang sudah di-encode
encoded_data.head()
# atribut/feature adalah dari kolom ketiga sampai kolom terakhir
X = encoded_data.iloc[:, 3:]
# target/class adalah kolom pertama; kolom kedua kita abaikan saja, karena merupakan negasi dari kolom pertama
Y = encoded_data.iloc[:, 1]

from sklearn.model_selection import train_test_split
# kita akan gunakan 10% dari seluruh dataset sebagai data testing
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.10, random_state=1234)

from sklearn.svm import SVC
# kita inisiasi SVM classifier kita menggunakan kernel radial (RBF)
clf = SVC(kernel='linear', gamma=0.1)
# latih SVM!
clf.fit(X_train, y_train)
y_train_predicted = clf.predict(X_train)

from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_train_predicted)
y_test_predicted = clf.predict(X_test)
accuracy_score(y_test, y_test_predicted)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_test_predicted))
print(confusion_matrix(y_test, y_test_predicted))